"""Authoritative legal database for India Cyber Law & Digital Rights Knowledge Center."""
from __future__ import annotations

from typing import List
from legal_knowledge.models import (
    CitizenActionGuide,
    GlossaryTerm,
    LegalInstrument,
    LegalScenario,
)

LEGAL_INSTRUMENTS: List[LegalInstrument] = [
    LegalInstrument(
        id="constitution-india",
        title="Constitution of India — Fundamental Digital Rights & Constitutional Remedies",
        short_title="Constitution of India (Articles 14, 19, 21, 32, 226)",
        year=1950,
        instrument_type="constitution_provision",
        category="constitutional_rights",
        responsible_authority="Supreme Court of India & High Courts",
        commencement_status="in_force",
        commencement_note="Fundamental rights in force since 26 January 1950. Fundamental Right to Privacy affirmed by 9-judge bench in 2017.",
        summary="The supreme legal framework of India guaranteeing equality before law (Art. 14), freedom of speech and expression (Art. 19(1)(a)), protection of life, liberty and informational privacy (Art. 21), and direct constitutional remedies before the Supreme Court (Art. 32) and High Courts (Art. 226).",
        why_it_matters_online="Guarantees that state actions affecting digital expression, internet shutdowns, surveillance, and personal data collection must satisfy constitutional tests of legality, legitimate state aim, necessity, and proportionality.",
        who_it_applies_to="Citizens and persons against the State (Union, State Governments, and instrumentalities under Article 12).",
        provisions=[
            {
                "section_or_article": "Article 21",
                "heading": "Right to Life, Personal Liberty & Informational Privacy",
                "plain_explanation": "Protects personal autonomy and informational privacy as an intrinsic part of life and liberty, as affirmed in the landmark 9-judge Constitution Bench judgment in Justice K. S. Puttaswamy (Retd.) v. Union of India (2017) 10 SCC 1.",
                "applicability_and_scope": "Applicable against state surveillance, unauthorized biometric/data collection, and arbitrary state intrusions.",
                "penalties_or_remedy": "Writ petitions for enforcement, quashing of unconstitutional rules, and declaration of fundamental rights violations.",
                "official_source_ref": "https://main.sci.gov.in/supremecourt/2012/35071/35071_2012_Judgement_24-Aug-2017.pdf",
            },
            {
                "section_or_article": "Article 19(1)(a)",
                "heading": "Freedom of Speech and Expression Online",
                "plain_explanation": "Guarantees freedom to express views, publish online, and access information over the internet, subject only to reasonable restrictions specified under Article 19(2) (sovereignty, security, public order, decency, defamation, incitement to an offence).",
                "applicability_and_scope": "Protects online journalism, digital discourse, and expression across platforms.",
                "penalties_or_remedy": "Judicial review of internet blocking orders and censorship directives under Anuradha Bhasin v. Union of India (2020) 3 SCC 637.",
                "official_source_ref": "https://www.indiacode.nic.in/handle/123456789/1522",
            },
            {
                "section_or_article": "Article 32 & Article 226",
                "heading": "Constitutional Writ Remedies (Habeas Corpus, Mandamus, Quo Warranto, Certiorari)",
                "plain_explanation": "Empowers citizens to approach the Supreme Court (Art. 32) or High Courts (Art. 226) directly when fundamental digital rights are infringed by state authorities or arbitrary executive action.",
                "applicability_and_scope": "Direct constitutional recourse for fundamental rights enforcement.",
                "penalties_or_remedy": "Issuance of binding writs, directions, or orders to public authorities.",
                "official_source_ref": "https://www.indiacode.nic.in/handle/123456789/1522",
            },
        ],
        real_world_scenarios=[
            "Challenging arbitrary internet suspension orders not complying with Telecom Suspension Rules.",
            "Challenging unauthorized governmental mass data collection without statutory backing.",
        ],
        limits_and_exceptions=[
            "Constitutional fundamental rights are primarily enforceable against the State and its instrumentalities, not purely private contractual disputes between private individuals.",
            "Online expression is subject to reasonable restrictions under Article 19(2).",
        ],
        citizen_remedies=[
            "File a Writ Petition under Article 226 before the jurisdictional High Court.",
            "File a Writ Petition under Article 32 before the Supreme Court for fundamental rights violation.",
        ],
        official_source_url="https://www.indiacode.nic.in/handle/123456789/1522",
        last_verified_at="2026-10-09T00:00:00Z",
    ),
    LegalInstrument(
        id="it-act-2000",
        title="Information Technology Act, 2000 (as amended)",
        short_title="Information Technology Act, 2000",
        year=2000,
        instrument_type="act",
        category="cyber_crimes",
        responsible_authority="Ministry of Electronics and Information Technology (MeitY)",
        commencement_status="in_force",
        commencement_note="Enacted on 9 June 2000; major amendments enacted via Information Technology (Amendment) Act, 2008 in force since 27 October 2009.",
        summary="The primary statutory framework in India for electronic governance, cybercrime offences, digital signatures, intermediary liabilities, cyber forensics, and cybersecurity powers.",
        why_it_matters_online="Defines specific cybercrimes including computer hacking, identity theft, cheating by impersonation using computer resources, unauthorized data extraction, and child sexual abuse material online.",
        who_it_applies_to="All persons within India and any person outside India if the act involves a computer, computer system, or computer network located in India (Section 75 extraterritorial jurisdiction).",
        provisions=[
            {
                "section_or_article": "Section 66C",
                "heading": "Punishment for Identity Theft",
                "plain_explanation": "Whoever, fraudulently or dishonestly, makes use of the electronic signature, password, or any other unique identification feature of any other person.",
                "applicability_and_scope": "Covers stealing passwords, OTPs, biometric credentials, UPI PINs, or SIM-swapping to access victim accounts.",
                "penalties_or_remedy": "Imprisonment of either description for a term which may extend to 3 years and fine up to ₹1,00,000.",
                "official_source_ref": "https://www.indiacode.nic.in/handle/123456789/1999",
            },
            {
                "section_or_article": "Section 66D",
                "heading": "Punishment for Cheating by Personation Using Computer Resource",
                "plain_explanation": "Whoever, by means of any communication device or computer resource, cheats by personation.",
                "applicability_and_scope": "Primary section applied to Digital Arrest scams, fake bank executive impersonation, phishing websites, and fake police video calls.",
                "penalties_or_remedy": "Imprisonment of either description for a term which may extend to 3 years and fine up to ₹1,00,000.",
                "official_source_ref": "https://www.indiacode.nic.in/handle/123456789/1999",
            },
            {
                "section_or_article": "Section 43 & 66",
                "heading": "Penalty for Damage to Computer System & Computer Related Offences (Hacking)",
                "plain_explanation": "Accessing computer systems without permission, downloading/copying data, introducing computer contaminants or malware (APKs, Trojans, Ransomware).",
                "applicability_and_scope": "Covers malware distribution, banking trojan APKs, ransomware attacks, and unauthorized system access.",
                "penalties_or_remedy": "Civil compensation under Section 43 up to ₹1 crore through Adjudicating Officer; Criminal punishment under Section 66 with imprisonment up to 3 years or fine up to ₹5 lakh.",
                "official_source_ref": "https://www.indiacode.nic.in/handle/123456789/1999",
            },
            {
                "section_or_article": "Section 70B",
                "heading": "Indian Computer Emergency Response Team (CERT-In) Powers & Reporting",
                "plain_explanation": "Designates CERT-In as national agency for incident response; empowers CERT-In to issue binding cybersecurity directions for reporting cyber incidents.",
                "applicability_and_scope": "Applies to service providers, intermediaries, data centres, and body corporates.",
                "penalties_or_remedy": "Non-compliance punishable under Section 70B(7) with imprisonment up to 1 year or fine up to ₹1 lakh.",
                "official_source_ref": "https://www.cert-in.org.in/Directions2022.jsp",
            },
        ],
        real_world_scenarios=[
            "Reporting a phishing website mimicking your bank's net-banking portal.",
            "Prosecuting fraudsters operating a Digital Arrest impersonation ring.",
            "Filing a claim for civil damages before the State IT Secretary (Adjudicating Officer) for unauthorized account debit.",
        ],
        limits_and_exceptions=[
            "Section 66A was struck down as unconstitutional by the Supreme Court in Shreya Singhal v. Union of India (2015) 5 SCC 1 and is no longer valid law.",
        ],
        citizen_remedies=[
            "Register FIR with Cyber Crime Police Station or via cybercrime.gov.in.",
            "File an application for compensation before the State Adjudicating Officer under Section 46 of the IT Act.",
        ],
        official_source_url="https://www.indiacode.nic.in/handle/123456789/1999",
        last_verified_at="2026-10-09T00:00:00Z",
    ),
    LegalInstrument(
        id="dpdp-act-2023",
        title="Digital Personal Data Protection Act, 2023 (DPDP Act) & DPDP Rules, 2025",
        short_title="Digital Personal Data Protection Act, 2023",
        year=2023,
        instrument_type="act",
        category="data_privacy",
        responsible_authority="Data Protection Board of India & Ministry of Electronics and Information Technology (MeitY)",
        commencement_status="phased_commencement",
        commencement_note="Assented by the President on 11 August 2023 (Act No. 22 of 2023). Operationalization underway following publication of draft DPDP Rules, 2025.",
        summary="India's dedicated data protection statute governing the processing of digital personal data. Establishes rights of Data Principals (citizens), obligations of Data Fiduciaries (entities collecting data), child data protections, and the Data Protection Board of India.",
        why_it_matters_online="Empowers individuals to know what personal data companies collect, request data erasure/correction, withdraw consent, and seek significant financial penalties (up to ₹250 crore) against organizations failing to protect against personal data breaches.",
        who_it_applies_to="Data Fiduciaries processing digital personal data within India, and outside India if offering goods or services to Data Principals within India.",
        provisions=[
            {
                "section_or_article": "Section 6",
                "heading": "Notice and Consent Architecture",
                "plain_explanation": "Data Fiduciaries must provide a clear, standalone notice in plain language (with English and 22 scheduled language options) before seeking consent, detailing data collected, purpose, and grievance mechanisms.",
                "applicability_and_scope": "Applies to every app, website, and digital platform collecting personal data.",
                "penalties_or_remedy": "Failure to obtain valid consent exposes fiduciary to board penalties.",
                "official_source_ref": "https://www.meity.gov.in/content/digital-personal-data-protection-act-2023",
            },
            {
                "section_or_article": "Section 8(6)",
                "heading": "Mandatory Personal Data Breach Notification",
                "plain_explanation": "In the event of a personal data breach, the Data Fiduciary must give intimation of such breach to the Data Protection Board of India and each affected Data Principal.",
                "applicability_and_scope": "Obligation on banks, telecom operators, e-commerce platforms, and data processors.",
                "penalties_or_remedy": "Failure to take reasonable security safeguards to prevent data breach punishable with penalty up to ₹250 crore (Schedule, Item 1).",
                "official_source_ref": "https://www.meity.gov.in/content/digital-personal-data-protection-act-2023",
            },
            {
                "section_or_article": "Sections 11, 12 & 13",
                "heading": "Rights of Data Principals (Citizens)",
                "plain_explanation": "Citizens have the right to access a summary of personal data processed, right to correction and erasure, right to grievance redressal, and right to nominate a representative.",
                "applicability_and_scope": "Enforceable by individual citizens against Data Fiduciaries.",
                "penalties_or_remedy": "Complaint to Data Fiduciary first, and subsequent appeal to Data Protection Board of India.",
                "official_source_ref": "https://www.meity.gov.in/content/digital-personal-data-protection-act-2023",
            },
        ],
        real_world_scenarios=[
            "Demanding an online lending app erase your phone contact list after loan closure.",
            "Holding an e-commerce platform accountable when customer personal records and order histories leak on the dark web.",
        ],
        limits_and_exceptions=[
            "Exemptions under Section 17 for state security, law enforcement investigation, research/statistical purposes, and processing of personal data made publicly available by the citizen themselves.",
        ],
        citizen_remedies=[
            "Submit a formal erasure/correction request to the Data Fiduciary's Grievance Officer.",
            "File a complaint before the Data Protection Board of India if the grievance is not resolved within the prescribed timeline.",
        ],
        official_source_url="https://www.meity.gov.in/content/digital-personal-data-protection-act-2023",
        last_verified_at="2026-10-09T00:00:00Z",
    ),
    LegalInstrument(
        id="bns-2023",
        title="Bharatiya Nyaya Sanhita, 2023 (BNS) — Cyber & Financial Offences",
        short_title="Bharatiya Nyaya Sanhita, 2023",
        year=2023,
        instrument_type="act",
        category="cyber_crimes",
        responsible_authority="Ministry of Home Affairs (MHA) & State Police Departments",
        commencement_status="in_force",
        commencement_note="In force across India since 1 July 2024, replacing the Indian Penal Code, 1860.",
        summary="The primary substantive criminal code of India containing modern provisions for cheating, personation, organized cybercrime, forgery of digital records, extortion, and criminal intimidation.",
        why_it_matters_online="Applied alongside the IT Act by police officers and courts to prosecute digital arrest extortion, fake UPI payment screenshots, organized online fraud syndicates, and financial cybercrimes.",
        who_it_applies_to="Any person committing offences within India, and offences committed outside India targeting computers or property in India.",
        provisions=[
            {
                "section_or_article": "Section 318(4)",
                "heading": "Cheating and Dishonestly Inducing Delivery of Property",
                "plain_explanation": "Cheating any person and thereby dishonestly inducing them to deliver any property, money, or valuable security.",
                "applicability_and_scope": "Applied to UPI QR scams, task investment fraud, and fake e-commerce stores.",
                "penalties_or_remedy": "Imprisonment of either description for a term which may extend to 7 years and fine.",
                "official_source_ref": "https://www.indiacode.nic.in/handle/123456789/2006",
            },
            {
                "section_or_article": "Section 319",
                "heading": "Cheating by Personation",
                "plain_explanation": "Cheating by pretending to be some other person, or knowingly substituting one person for another, or representing that he or any other person is a person other than he really is.",
                "applicability_and_scope": "Applied to deepfake voice/video impersonation, fake customer care handles, and matrimonial romance frauds.",
                "penalties_or_remedy": "Imprisonment of either description for a term which may extend to 5 years, or fine, or both.",
                "official_source_ref": "https://www.indiacode.nic.in/handle/123456789/2006",
            },
            {
                "section_or_article": "Section 336 & 338",
                "heading": "Forgery and Forgery of Electronic Record",
                "plain_explanation": "Making false electronic records (fake payment confirmations, forged arrest warrants, cloned bank notices) with intent to cause damage or commit fraud.",
                "applicability_and_scope": "Fabricating fake CBI/Police notices in Digital Arrest, fake UPI transaction success screens.",
                "penalties_or_remedy": "Imprisonment of either description for a term which may extend to 2 to 7 years and fine.",
                "official_source_ref": "https://www.indiacode.nic.in/handle/123456789/2006",
            },
        ],
        real_world_scenarios=[
            "Prosecuting a scammer who created forged police arrest warrants sent via WhatsApp.",
            "Registering FIR against fraudsters who used fake UPI payment screenshots to collect goods.",
        ],
        limits_and_exceptions=[
            "Requires establishing mens rea (criminal intent / dishonest intention) beyond reasonable doubt.",
        ],
        citizen_remedies=[
            "Lodge an FIR with the nearest police station or through cybercrime.gov.in.",
            "Seek freezing of fraudulent bank accounts under BNSS procedural provisions.",
        ],
        official_source_url="https://www.indiacode.nic.in/handle/123456789/2006",
        last_verified_at="2026-10-09T00:00:00Z",
    ),
    LegalInstrument(
        id="bsa-2023",
        title="Bharatiya Sakshya Adhiniyam, 2023 (BSA) — Digital & Electronic Evidence",
        short_title="Bharatiya Sakshya Adhiniyam, 2023 (Sections 61 & 63)",
        year=2023,
        instrument_type="act",
        category="telecom_evidence",
        responsible_authority="Judiciary of India & Law Enforcement Agencies",
        commencement_status="in_force",
        commencement_note="In force since 1 July 2024, replacing the Indian Evidence Act, 1872.",
        summary="Governs the admissibility, authentication, and proof of electronic and digital records in Indian judicial proceedings.",
        why_it_matters_online="Prescribes how screenshots, server logs, WhatsApp exports, bank statements, and email headers must be legally preserved and certified to be admissible in court during cybercrime trials.",
        who_it_applies_to="Complainants, victims, forensic examiners, and police submitting digital evidence in court.",
        provisions=[
            {
                "section_or_article": "Section 61",
                "heading": "Admissibility of Electronic or Digital Record",
                "plain_explanation": "Affirms that digital records shall have the same legal effect, validity and enforceability as other paper documents.",
                "applicability_and_scope": "Applies to emails, chats, audio files, video calls, server logs, and transaction hashes.",
                "penalties_or_remedy": "Enables victims to present digital proof directly in criminal proceedings.",
                "official_source_ref": "https://www.indiacode.nic.in/handle/123456789/2008",
            },
            {
                "section_or_article": "Section 63",
                "heading": "Admissibility of Electronic Records and Certificate Requirements",
                "plain_explanation": "Replaces erstwhile Section 65B of Evidence Act. Governs conditions for computer output printouts, requiring a certificate signed by a person occupying a responsible official position in relation to the operation of the device.",
                "applicability_and_scope": "Essential for presenting WhatsApp screenshots, call records, and bank transaction slips.",
                "penalties_or_remedy": "Ensures evidence cannot be dismissed as secondary/unverified hearsay.",
                "official_source_ref": "https://www.indiacode.nic.in/handle/123456789/2008",
            },
        ],
        real_world_scenarios=[
            "Preserving raw WhatsApp chat exports and transaction receipts for cyber police FIR.",
            "Submitting bank server logs in consumer court dispute.",
        ],
        limits_and_exceptions=[
            "Tampered, unverified, or cropped screenshots without device metadata and Section 63 certificate may face evidentiary challenge in trial court.",
        ],
        citizen_remedies=[
            "Preserve original device storage, uncropped full screenshots, and raw exported chat archives.",
        ],
        official_source_url="https://www.indiacode.nic.in/handle/123456789/2008",
        last_verified_at="2026-10-09T00:00:00Z",
    ),
    LegalInstrument(
        id="rbi-customer-protection",
        title="RBI Master Direction — Customer Protection: Limiting Liability in Unauthorized Electronic Banking Transactions",
        short_title="RBI Customer Protection Master Circular",
        year=2017,
        instrument_type="master_direction",
        category="digital_payments",
        responsible_authority="Reserve Bank of India (RBI)",
        commencement_status="active_regulation",
        commencement_note="Circular DBR.No.Leg.BC.78/09.07.005/2017-18 dated July 6, 2017, active and binding across all Commercial Banks, Payment Banks, and Small Finance Banks.",
        summary="The binding Reserve Bank of India framework establishing Zero Liability and Limited Liability protections for bank account holders in cases of unauthorized digital and card transactions.",
        why_it_matters_online="Guarantees that if you report an unauthorized electronic banking fraud within 3 working days where the fault does not lie with you, the bank MUST credit the entire lost amount to your account within 10 working days.",
        who_it_applies_to="All Scheduled Commercial Banks, Payment Banks, Co-operative Banks, and their customers in India.",
        provisions=[
            {
                "section_or_article": "Paragraph 6",
                "heading": "Zero Liability of Customer",
                "plain_explanation": "A customer has ZERO liability in cases of: (a) Contributory fraud/negligence on the part of the bank, or (b) Third-party breach where deficiency lies neither with bank nor customer, but customer notifies bank within 3 working days of receiving alert.",
                "applicability_and_scope": "Unauthorized net banking debits, cloned cards, and malware unauthorized transfers.",
                "penalties_or_remedy": "Full shadow reversal/credit to customer account within 10 working days.",
                "official_source_ref": "https://www.rbi.org.in/scripts/BS_CircularIndexDisplay.aspx?Id=11040",
            },
            {
                "section_or_article": "Paragraph 7 & 8",
                "heading": "Limited Liability for Delayed Reporting",
                "plain_explanation": "If reported between 4 to 7 working days, customer liability is capped at ₹5,000 (basic savings), ₹10,000 (savings/credit cards up to ₹5 lakh limit), or ₹25,000 (current accounts). If reported beyond 7 days, as per board-approved bank policy.",
                "applicability_and_scope": "Third-party digital fraud reported within 4-7 days.",
                "penalties_or_remedy": "Bank reimburses all losses above the statutory cap.",
                "official_source_ref": "https://www.rbi.org.in/scripts/BS_CircularIndexDisplay.aspx?Id=11040",
            },
            {
                "section_or_article": "Paragraph 9",
                "heading": "Burden of Proof on the Bank",
                "plain_explanation": "The burden of proving customer negligence in unauthorized electronic banking transactions lies entirely on the bank, not the consumer.",
                "applicability_and_scope": "Disputes before Banking Ombudsman and Consumer Courts.",
                "penalties_or_remedy": "Bank cannot deny claim without proving customer voluntarily shared OTP/credentials.",
                "official_source_ref": "https://www.rbi.org.in/scripts/BS_CircularIndexDisplay.aspx?Id=11040",
            },
        ],
        real_world_scenarios=[
            "Unrecognized midnight debit of ₹85,000 reported to bank within 24 hours.",
            "SIM swap fraud resulting in unauthorized IMPS transfers.",
        ],
        limits_and_exceptions=[
            "Where customer voluntarily shares their OTP, PIN, or password with a scammer, customer bears liability until the transaction is reported to the bank.",
        ],
        citizen_remedies=[
            "Lodge immediate written complaint with bank Branch Manager and obtain Complaint Acknowledgement Number.",
            "Escalate to Bank Principal Nodal Officer if unresolved within 30 days.",
            "File complaint with RBI Integrated Banking Ombudsman at https://cms.rbi.org.in.",
        ],
        official_source_url="https://www.rbi.org.in/scripts/BS_CircularIndexDisplay.aspx?Id=11040",
        last_verified_at="2026-10-09T00:00:00Z",
    ),
]

LEGAL_SCENARIOS: List[LegalScenario] = [
    LegalScenario(
        id="scenario-upi-theft",
        title="Unauthorized Money Debit via UPI or Mobile Banking",
        icon_name="CreditCard",
        user_situation="Money was deducted from my bank account via UPI, Google Pay, PhonePe, or Net Banking without my authorized approval, or I was tricked into scanning a QR code.",
        what_is_happening="Fraudulent debit triggered via manipulated collect requests, unauthorized SIM swap, or credential phishing.",
        potentially_applicable_laws=[
            {"law": "RBI Master Direction on Customer Protection (2017)", "relevance": "Zero liability if reported within 3 days; burden of proof on bank."},
            {"law": "Section 66C & 66D, IT Act 2000", "relevance": "Identity theft and cheating by personation using computer resource."},
            {"law": "Section 318(4), BNS 2023", "relevance": "Criminal cheating and dishonestly inducing delivery of money."},
        ],
        immediate_citizen_actions=[
            "Dial 1930 (National Cybercrime Financial Helpline) immediately — the 'Golden Hour' is critical to freeze money in recipient mule accounts.",
            "Open your UPI app and select 'Report Fraudulent Transaction'.",
            "Call your bank's 24/7 fraud helpline and request immediate hotlisting of UPI and card services.",
            "Submit a formal written complaint to your bank branch within 3 working days to invoke RBI Zero Liability protection.",
        ],
        evidence_preservation_tips=[
            "Download and save bank account statement showing date, timestamp, and 12-digit UPI UTR / RRN reference number.",
            "Take uncropped screenshots of the SMS debit notification, UPI app transaction receipt, and scammer chat history.",
        ],
        official_reporting_portal="National Cyber Crime Reporting Portal & 1930 Helpline",
        portal_url="https://cybercrime.gov.in/",
        helpline_number="1930",
        legal_caveat="Under RBI rules, if you voluntarily shared your UPI PIN or OTP, your liability remains until you notify the bank to block further access.",
    ),
    LegalScenario(
        id="scenario-digital-arrest",
        title="Targeted by 'Digital Arrest' or Fake Police / CBI Video Call",
        icon_name="ShieldAlert",
        user_situation="Someone on WhatsApp or Skype claiming to be from Mumbai Police, CBI, ED, or Customs tells me my Aadhaar is linked to drugs/money laundering and places me under 'Digital Arrest'.",
        what_is_happening="Organized extortion syndicate using fear tactics, forged warrants, and fake police studio sets.",
        potentially_applicable_laws=[
            {"law": "Section 204, BNS 2023", "relevance": "Personating a public servant (police/customs)."},
            {"law": "Section 308, BNS 2023", "relevance": "Extortion by putting a person in fear of injury or arrest."},
            {"law": "Section 66D, IT Act 2000", "relevance": "Cheating by personation using computer resource."},
            {"law": "Section 336/338, BNS 2023", "relevance": "Forgery of official seals and electronic warrants."},
        ],
        immediate_citizen_actions=[
            "Immediately disconnect the video call. Do not panic. 'Digital Arrest' DOES NOT EXIST under Indian criminal law.",
            "Do not transfer any money to any 'safe account' or 'verification account'.",
            "Talk to family members or visit your local police station in person to verify.",
            "Report the phone numbers and WhatsApp IDs to 1930 and cybercrime.gov.in.",
        ],
        evidence_preservation_tips=[
            "Save screenshots of the forged warrants, police notices, and caller profile pictures.",
            "Note down the caller phone numbers, Skype IDs, and any bank account numbers they provided for fund transfer.",
        ],
        official_reporting_portal="I4C National Cyber Crime Reporting Portal",
        portal_url="https://cybercrime.gov.in/",
        helpline_number="1930",
        legal_caveat="No Indian police officer or magistrate can conduct an arrest, trial, or demand bail bond deposits over WhatsApp or Skype video calls.",
    ),
    LegalScenario(
        id="scenario-data-breach",
        title="My Personal Data or Password Was Leaked Online",
        icon_name="Lock",
        user_situation="My phone number, Aadhaar, password, or financial records were leaked online from a website database or dark web forum.",
        what_is_happening="Personal data breach and unauthorized disclosure by a Data Fiduciary or third-party processor.",
        potentially_applicable_laws=[
            {"law": "Section 8(6) & Section 33, DPDP Act 2023", "relevance": "Mandatory breach notification and penalty up to ₹250 crore for failing security safeguards."},
            {"law": "Article 21, Constitution of India", "relevance": "Fundamental Right to Informational Privacy under Puttaswamy judgment."},
            {"law": "Section 43A / 72A, IT Act 2000", "relevance": "Compensation for failure to protect data and disclosure of information in breach of lawful contract."},
        ],
        immediate_citizen_actions=[
            "Immediately change passwords across all accounts sharing the leaked password; enable Hardware 2FA or Authenticator App.",
            "Lock your biometric data on the official UIDAI portal (mAadhaar app).",
            "Send a formal notice to the Data Fiduciary's Grievance Officer requesting an audit and erasure of compromised data.",
        ],
        evidence_preservation_tips=[
            "Save breach notifications, emails, or public disclosure links identifying the breached service.",
        ],
        official_reporting_portal="Data Protection Board of India & CERT-In Incident Reporting",
        portal_url="https://www.cert-in.org.in/",
        helpline_number="1800-11-4949",
        legal_caveat="Under the DPDP Act 2023, you have the statutory right to request erasure and explanation from the Data Fiduciary regarding how your data was processed.",
    ),
]

GLOSSARY_TERMS: List[GlossaryTerm] = [
    GlossaryTerm(
        id="term-digital-arrest",
        term="Digital Arrest (Myth vs Reality)",
        plain_definition="A cyber extortion scam where criminals impersonate police officers on video calls claiming the victim is under house arrest. Indian law contains NO concept of digital arrest.",
        legal_definition="Fraudulent personation of a public servant (Section 204 BNS) and extortion (Section 308 BNS) punishable with severe imprisonment.",
        statutory_reference="BNS 2023 Sections 204, 308, 318; IT Act Section 66D",
        example="A caller on Skype showing a fake CBI badge threatening to arrest you unless you transfer ₹5 lakh to an escrow account.",
    ),
    GlossaryTerm(
        id="term-golden-hour",
        term="Financial Golden Hour (1930 Helpline)",
        plain_definition="The critical initial 1 to 2 hours immediately following an unauthorized bank or UPI debit where police can freeze the stolen money before scammers cash out.",
        legal_definition="Immediate administrative freeze mechanism coordinated by I4C and participating banks via the National Cybercrime Reporting Portal.",
        statutory_reference="MHA / I4C Standard Operating Procedure for Financial Cyber Fraud",
        example="Dialing 1930 within 30 minutes of a ₹50,000 debit allows I4C to instruct the beneficiary bank to freeze the recipient mule account.",
    ),
    GlossaryTerm(
        id="term-data-principal",
        term="Data Principal",
        plain_definition="The individual (citizen) to whom personal data relates.",
        legal_definition="Defined under Section 2(j) of the Digital Personal Data Protection Act, 2023 as the individual to whom the personal data relates and includes parents in case of a child.",
        statutory_reference="DPDP Act 2023, Section 2(j)",
        example="You, as a user registering an account on an online shopping portal.",
    ),
    GlossaryTerm(
        id="term-section-63-cert",
        term="Section 63 Certificate (BSA 2023)",
        plain_definition="A signed legal certificate proving that a digital printout, chat log, or screenshot accurately reflects the original electronic device data without tampering.",
        legal_definition="Mandatory evidentiary requirement under Section 63 of Bharatiya Sakshya Adhiniyam, 2023 for admissibility of electronic records in court.",
        statutory_reference="Bharatiya Sakshya Adhiniyam 2023, Section 63",
        example="A signed statement accompanying WhatsApp screenshots submitted to a court in a cyber fraud trial.",
    ),
]

CITIZEN_ACTION_GUIDES: List[CitizenActionGuide] = [
    CitizenActionGuide(
        id="guide-upi-fraud-immediate",
        title="Immediate Emergency Action: UPI / Banking Cyber Fraud",
        category="financial_emergency",
        urgency_level="immediate_golden_hour",
        summary="Exact steps to take within the first 60 minutes of unauthorized money debit to maximize the chance of recovering funds.",
        step_by_step=[
            {"step": "Step 1: Call 1930 Immediately", "action": "Dial 1930 from your phone. Provide the victim bank name, account number, transaction UTR/RRN, timestamp, and amount lost to trigger an I4C freeze."},
            {"step": "Step 2: Lodge Portal Complaint", "action": "Visit cybercrime.gov.in and file a complaint under 'Financial Fraud'. Note down the Acknowledgement Number."},
            {"step": "Step 3: Notify Bank in Writing", "action": "Email and visit your home bank branch within 3 days with the complaint copy to claim RBI Zero Liability protection."},
            {"step": "Step 4: Block Cards & Net Banking", "action": "Temporarily block net banking and UPI access to prevent subsequent automated debit attempts."},
        ],
        dos_and_donts={
            "dos": [
                "Preserve unedited SMS messages containing transaction references and UTR numbers.",
                "Keep note of the 1930 complaint ticket number for following up with your bank nodal officer.",
                "Submit a written complaint to your bank branch within 3 working days.",
            ],
            "donts": [
                "Never search for bank helpline numbers on Google Maps or social media (they are often scammer numbers).",
                "Never share your OTP or UPI PIN with anyone claiming to help you recover lost funds.",
                "Do not delete your WhatsApp chats or call logs with the scammer.",
            ],
        },
        official_channels=[
            {"channel": "National Cybercrime Helpline", "value": "1930 (Toll-Free, 24/7)"},
            {"channel": "Official Portal", "value": "https://cybercrime.gov.in"},
            {"channel": "RBI Banking Ombudsman", "value": "https://cms.rbi.org.in (Call 14448)"},
        ],
        disclaimer="This guide provides educational legal information under Indian law and does not constitute individualized legal advice. Always consult a qualified advocate for specific litigation.",
    ),
    CitizenActionGuide(
        id="guide-evidence-preservation",
        title="How to Preserve Electronic Evidence for Cyber Police & Court (BSA 2023)",
        category="evidence_forensics",
        urgency_level="priority_24h",
        summary="How to record, save, and certify digital evidence so it cannot be rejected by cyber police or challenged in court under Section 63 of Bharatiya Sakshya Adhiniyam, 2023.",
        step_by_step=[
            {"step": "Step 1: Full Uncropped Screenshots", "action": "Capture full-screen screenshots showing the complete URL bar, phone status bar with date and time, and sender phone numbers."},
            {"step": "Step 2: Export Raw Chat Archives", "action": "In WhatsApp or Telegram, use 'Export Chat without Media' and save the resulting `.txt` file with raw timestamps."},
            {"step": "Step 3: Save Original Email Headers", "action": "In Gmail or Outlook, click 'Show Original' / 'View Message Headers' and download the `.eml` or `.msg` file."},
            {"step": "Step 4: Bank Statement Download", "action": "Download the official PDF account statement directly from net banking showing 12-digit UTR and IMPS reference codes."},
        ],
        dos_and_donts={
            "dos": [
                "Keep the original smartphone or laptop without resetting it until the investigation is complete.",
                "Store backups of digital evidence in a secure, non-tampered cloud drive or external USB.",
            ],
            "donts": [
                "Do not crop screenshots to remove dates, battery icons, or top status bars.",
                "Do not edit or rename original text files containing message exports.",
            ],
        },
        official_channels=[
            {"channel": "National Cyber Crime Reporting Portal", "value": "https://cybercrime.gov.in"},
            {"channel": "CERT-In Incident Reporting", "value": "incident@cert-in.org.in"},
        ],
        disclaimer="Prepared in accordance with electronic evidence standards under Bharatiya Sakshya Adhiniyam, 2023.",
    ),
]
