"""Authoritative documented scam cases verified from official public cyber-safety advisories."""
from __future__ import annotations

from typing import List
from scam_broadcast.models import ScamCaseBroadcast

VERIFIED_DOCUMENTED_CASES: List[ScamCaseBroadcast] = [
    ScamCaseBroadcast(
        id="case-digital-arrest-01",
        slug="digital-arrest-law-enforcement-impersonation",
        title="Digital Arrest Scam: Impersonation of Police, CBI, and Customs Officials",
        status="ongoing_campaign",
        severity="critical",
        scam_type="digital_arrest",
        category_display="Digital Arrest & Law Enforcement Impersonation",
        summary="Fraudsters initiate video calls posing as police officers, CBI agents, or Customs officials, creating fake studio backgrounds with police insignia. Victims are told a parcel with illegal contraband (drugs/fake passports) was found in their name, and they are placed under a fake 'Digital Arrest' until they transfer funds to 'RBI verification accounts'.",
        what_happened="Multiple documented incidents nationwide where victims, particularly senior citizens and professionals, were coerced through extended WhatsApp/Skype video calls into transferring life savings into mule accounts under the threat of immediate arrest. Prime Minister's Mann Ki Baat address and MHA/I4C issued public warnings clarifying that 'Digital Arrest' does not exist under Indian law.",
        attack_chain=[
            {
                "step_number": 1,
                "stage_name": "First Contact & Fear Hook",
                "description": "Victim receives an automated IVR call claiming a FedEx/courier parcel containing illegal drugs or passports linked to their Aadhaar has been intercepted.",
                "attacker_action": "Places automated spoofed calls claiming customs interception.",
                "victim_experience": "Hears an urgent automated alert claiming customs or police hold.",
            },
            {
                "step_number": 2,
                "stage_name": "Transfer to Fake Police Station",
                "description": "Call is routed to a fake investigator on WhatsApp/Skype in police uniform seated before a staged police backdrop.",
                "attacker_action": "Displays forged arrest warrants, FIR copies with fake Supreme Court/CBI seals.",
                "victim_experience": "Intimidated by official-looking documents and uniform.",
            },
            {
                "step_number": 3,
                "stage_name": "Digital Arrest & Isolation",
                "description": "Victim is ordered not to disconnect the video call, tell family members, or leave the room for 24-72 hours under 'secret national security protocol'.",
                "attacker_action": "Monitors the victim continuously to prevent third-party intervention.",
                "victim_experience": "Kept in extreme isolation and psychological distress.",
            },
            {
                "step_number": 4,
                "stage_name": "Fund Transfer for 'Clearance'",
                "description": "Fraudsters demand funds be transferred to an 'escrow / RBI verification account' that will allegedly be refunded after financial audit.",
                "attacker_action": "Siphons funds through multi-tier mule accounts and crypto exits.",
                "victim_experience": "Transfers funds via RTGS/IMPS believing it is an official government audit.",
            },
        ],
        target_audience="Senior citizens, retirees, healthcare professionals, and working individuals.",
        warning_signs=[
            "Claims of 'Digital Arrest' over WhatsApp, Skype, or phone call (No law in India permits arrest via video call).",
            "Demands to keep the video call open 24/7 and maintain secrecy from family or bank managers.",
            "Display of arrest warrants or Supreme Court notices via WhatsApp messaging.",
            "Demand to transfer money to a 'government verification account' or 'RBI safe account'.",
        ],
        technical_indicators=[
            {"type": "caller_pattern", "value": "+92 / international VoIP numbers spoofed as Indian agencies", "safe_display": "VoIP / WhatsApp Caller Spoofing", "linked_indicator_id": None},
            {"type": "domain", "value": "cbi-verification-portal.online", "safe_display": "cbi-verification-portal.online (Fake Clearance Portal)", "linked_indicator_id": None},
        ],
        documented_impact="Over ₹1,750 crore reported siphoned nationwide across 2023-2024 via Digital Arrest schemes as reported by the Indian Cyber Crime Coordination Centre (I4C).",
        protection_steps=[
            "Immediately disconnect any call where someone threatens 'Digital Arrest' or claims your Aadhaar is linked to illegal narcotics.",
            "Remember that Indian police and law enforcement agencies NEVER conduct arrests or interrogation over WhatsApp or Skype video calls.",
            "Never transfer money to any bank account for 'clearance' or 'verification'.",
            "Verify any legitimate police inquiry by visiting your local police station in person.",
        ],
        victim_recovery_steps=[
            "Immediately call the National Financial Cyber Fraud Helpline at 1930 to freeze transactions in the golden hour.",
            "Register a formal complaint on the official portal at cybercrime.gov.in.",
            "Notify your bank branch manager immediately to initiate chargeback / freeze on beneficiary accounts.",
            "Preserve screenshots of chat logs, video call records, caller numbers, and transaction IDs.",
        ],
        legal_provisions=[
            {"instrument_id": "it-act-2000", "provision": "Section 66D, Information Technology Act, 2000", "title": "Cheating by Personation Using Computer Resource", "summary": "Punishable with imprisonment up to 3 years and fine up to ₹1 lakh."},
            {"instrument_id": "bns-2023", "provision": "Section 318(4), Bharatiya Nyaya Sanhita, 2023", "title": "Cheating and Dishonestly Inducing Delivery of Property", "summary": "Punishable with imprisonment up to 7 years and fine."},
            {"instrument_id": "bns-2023", "provision": "Section 204, Bharatiya Nyaya Sanhita, 2023", "title": "Personating a Public Servant", "summary": "Punishable with imprisonment and fine for impersonating police/government authorities."},
        ],
        primary_source="Indian Cyber Crime Coordination Centre (I4C), Ministry of Home Affairs (MHA)",
        source_url="https://cybercrime.gov.in/",
        published_at="2024-05-14T10:00:00Z",
        last_verified_at="2026-10-09T00:00:00Z",
        is_breaking=True,
    ),
    ScamCaseBroadcast(
        id="case-upi-qr-02",
        slug="upi-qr-code-receive-money-deception",
        title="UPI QR Code 'Scan to Receive Money' Reverse Payment Scam",
        status="confirmed_active",
        severity="high",
        scam_type="upi_qr_fraud",
        category_display="UPI & QR Code Deception",
        summary="Fraudsters pretending to buy items on OLX/Marketplace or sending 'cashback rewards' instruct victims to scan a QR code or approve a collect request on PhonePe, Google Pay, or Paytm to 'receive' money. Entering the UPI PIN immediately debits money from the victim's account.",
        what_happened="Mass consumer fraud targeting online sellers, marketplace users, and cashback seekers. Fraudsters manipulate victims by creating urgency and convincing them that entering their UPI PIN is required for money to be credited into their account.",
        attack_chain=[
            {
                "step_number": 1,
                "stage_name": "Listing Response on Marketplace",
                "description": "Victim posts an item for sale on OLX or Quikr. Attacker contacts immediately offering full asking price without negotiation.",
                "attacker_action": "Poses as an army officer or distant buyer eager to buy immediately.",
                "victim_experience": "Believes they found a genuine, eager customer.",
            },
            {
                "step_number": 2,
                "stage_name": "Fake Advance Payment QR",
                "description": "Attacker claims they can only pay via military wallet or merchant UPI, sending a QR code via WhatsApp with text 'Scan to Receive ₹15,000'.",
                "attacker_action": "Generates a merchant collect request or debit QR code.",
                "victim_experience": "Opens their UPI app and scans the QR code.",
            },
            {
                "step_number": 3,
                "stage_name": "PIN Entry Coercion",
                "description": "UPI app prompts for UPI PIN. Attacker insists 'enter your PIN to verify receiving the deposit'.",
                "attacker_action": "Rushes the victim on voice call to prevent them reading the debit prompt.",
                "victim_experience": "Enters PIN expecting credit, and account is immediately debited.",
            },
        ],
        target_audience="Individual online sellers, small shop owners, and digital payment users.",
        warning_signs=[
            "Anyone asking you to scan a QR code or enter your UPI PIN to RECEIVE money (UPI PIN is ONLY required to send/pay money).",
            "Buyer agreeing to purchase without seeing the item or negotiating the price.",
            "Collect requests on PhonePe/GPay appearing as 'Approval for Payment'.",
        ],
        technical_indicators=[
            {"type": "pattern", "value": "UPI Collect Request: VPA merchant payment disguised as refund", "safe_display": "Disguised UPI Collect Request", "linked_indicator_id": None},
        ],
        documented_impact="Over 40% of financial fraud complaints registered on the 1930 helpline in 2023 involved UPI payment manipulation and fake collect requests according to NPCI and I4C data.",
        protection_steps=[
            "Fundamental Rule of UPI: You NEVER need to enter your UPI PIN to receive money.",
            "Never scan a QR code sent by a buyer or unknown contact.",
            "Decline all unverified collect payment requests on your UPI apps.",
        ],
        victim_recovery_steps=[
            "Call 1930 immediately within the first hour of fraudulent debit.",
            "Report the fraudulent transaction within your UPI application (Google Pay / PhonePe / Paytm / BHIM) under 'Report Fraud'.",
            "Contact your home bank branch to log a dispute under RBI Master Directions on Customer Protection.",
        ],
        legal_provisions=[
            {"instrument_id": "rbi-customer-protection", "provision": "RBI Master Direction on Customer Protection — Limiting Liability", "title": "Zero Liability in Contributory Bank Fraud / Third-Party Breach", "summary": "Full compensation within 3 working days if customer reports third-party fraud within 3 days."},
            {"instrument_id": "it-act-2000", "provision": "Section 66C, Information Technology Act, 2000", "title": "Punishment for Identity Theft (Misuse of Electronic Signature/PIN)", "summary": "Imprisonment up to 3 years and fine up to ₹1 lakh."},
        ],
        primary_source="National Payments Corporation of India (NPCI) & Reserve Bank of India (RBI)",
        source_url="https://www.rbi.org.in/",
        published_at="2024-03-20T09:00:00Z",
        last_verified_at="2026-10-09T00:00:00Z",
        is_breaking=False,
    ),
    ScamCaseBroadcast(
        id="case-banking-apk-03",
        slug="malicious-banking-apk-kyc-expiry-scam",
        title="Malicious Banking APK & Fake KYC Expiry Phishing Campaign",
        status="confirmed_active",
        severity="critical",
        scam_type="malicious_apk",
        category_display="Malicious APKs & Banking Impersonation",
        summary="Smishing campaign distributing malicious Android APK files disguised as official banking apps (e.g., 'SBI_Reward.apk', 'YONO_Update.apk', 'HDFC_NetBanking.apk') via SMS claiming imminent account suspension or KYC expiry. The installed Trojan intercepts OTPs, SMS, and net-banking credentials.",
        what_happened="CERT-In issued security alert CIAD-2024-0012 warning users against widespread SMS campaigns targeting State Bank of India, HDFC Bank, PNB, and ICICI Bank customers. The APKs request SMS and accessibility permissions, forwarding all two-factor authentication OTPs directly to attacker C2 servers.",
        attack_chain=[
            {
                "step_number": 1,
                "stage_name": "Urgent SMS Threat",
                "description": "Victim receives SMS: 'Dear Customer, your SBI account will be blocked today due to pending PAN/KYC update. Update immediately at http://sbi-kyc-verify.in/sbi.apk'.",
                "attacker_action": "Sends mass SMS spoofing official bank sender IDs via compromised SMS gateways.",
                "victim_experience": "Panics upon seeing imminent bank block threat.",
            },
            {
                "step_number": 2,
                "stage_name": "Sideloading Malicious APK",
                "description": "Website downloads an `.apk` file and prompts the victim to 'Allow installation from unknown sources' in Android settings.",
                "attacker_action": "Bypasses Google Play Protect through sideloading instructions.",
                "victim_experience": "Installs the app believing it is official bank software.",
            },
            {
                "step_number": 3,
                "stage_name": "Credential & Permission Capture",
                "description": "App displays a clone login interface capturing username, password, card number, and CVV, while silently obtaining SMS read/send permissions.",
                "attacker_action": "Intercepts incoming bank OTPs and initiates high-value transfers.",
                "victim_experience": "Sees a loading screen while attacker empties the account in the background.",
            },
        ],
        target_audience="Bank account holders with Android mobile devices.",
        warning_signs=[
            "SMS with generic links ending in `.apk` or requesting sideloading of bank apps.",
            "Urgent threats of immediate bank account block, SIM deactivation, or reward expiration.",
            "Any bank app not downloaded directly from Google Play Store or Apple App Store.",
        ],
        technical_indicators=[
            {"type": "url", "value": "http://sbi-kyc-reward-portal.xyz/app.apk", "safe_display": "http://sbi-kyc-reward-portal.xyz/app.apk (Malicious APK Host)", "linked_indicator_id": None},
            {"type": "domain", "value": "hdfc-rewards-redeem.online", "safe_display": "hdfc-rewards-redeem.online (Phishing Landing Page)", "linked_indicator_id": None},
        ],
        documented_impact="Over 25,000 infected Android devices documented across 14 states as cited in CERT-In Technical Advisory CIAD-2024-0012.",
        protection_steps=[
            "Never download or install any banking application from a website link or SMS. Only use Google Play Store or Apple App Store.",
            "Keep 'Install Unknown Apps' permanently disabled in your Android security settings.",
            "Remember that banks never send APK links via SMS to complete KYC.",
        ],
        victim_recovery_steps=[
            "Immediately turn on Airplane Mode or disconnect internet to stop malware from sending OTPs.",
            "Uninstall the malicious app via Android Safe Mode or perform a full factory reset.",
            "Call 1930 and contact your bank from another phone to immediately block net banking, debit cards, and UPI access.",
        ],
        legal_provisions=[
            {"instrument_id": "it-act-2000", "provision": "Section 43 & Section 66, IT Act, 2000", "title": "Penalty and Compensation for Damage to Computer System & Hacking", "summary": "Civil damages up to ₹1 crore and criminal imprisonment up to 3 years."},
            {"instrument_id": "it-act-2000", "provision": "Section 66E, IT Act, 2000", "title": "Violation of Privacy (Unauthorized Interception)", "summary": "Imprisonment up to 3 years or fine up to ₹2 lakh."},
        ],
        primary_source="Indian Computer Emergency Response Team (CERT-In)",
        source_url="https://www.cert-in.org.in/",
        published_at="2024-04-18T14:30:00Z",
        last_verified_at="2026-10-09T00:00:00Z",
        is_breaking=True,
    ),
    ScamCaseBroadcast(
        id="case-job-task-04",
        slug="task-based-part-time-job-telegram-scam",
        title="Part-Time Job & Task-Based Rating Investment Fraud",
        status="ongoing_campaign",
        severity="high",
        scam_type="investment_part_time_job",
        category_display="Task-Based Job & Investment Fraud",
        summary="Victims are approached via WhatsApp or Telegram offering work-from-home jobs paying ₹3,000–₹8,000 per day for liking YouTube videos, reviewing Google Maps hotels, or rating movies. After paying small initial incentives to build trust, victims are lured into 'prepaid merchant tasks' and crypto deposits that cannot be withdrawn.",
        what_happened="Nationwide multi-tier cyber syndicate uncovered by I4C and state cyber police. Victims are added to Telegram VIP investment groups filled with fake member screenshots showing massive profits. Once high deposits (₹50,000 to ₹25 lakh) are made, the portal blocks withdrawals demanding 'income tax fees' or 'handling charges'.",
        attack_chain=[
            {
                "step_number": 1,
                "stage_name": "Unsolicited Job Offer",
                "description": "WhatsApp message from international number (+84, +62, +254): 'HR from Global Marketing. Earn ₹500 per 3 YouTube likes'.",
                "attacker_action": "Sends mass unsolicited messages.",
                "victim_experience": "Performs simple task and receives actual ₹150 UPI payment.",
            },
            {
                "step_number": 2,
                "stage_name": "Move to Telegram VIP Channel",
                "description": "Victim is added to a Telegram group with 'Tutors' and bots posting fake screenshots of earnings.",
                "attacker_action": "Creates fabricated social proof and peer validation.",
                "victim_experience": "Feels confident due to small initial profit payout.",
            },
            {
                "step_number": 3,
                "stage_name": "Prepaid Investment Tasks",
                "description": "Attacker introduces 'VIP Commission Tasks' requiring initial deposit of ₹5,000 to unlock ₹8,000 reward, scaling up to ₹1,00,000+.",
                "attacker_action": "Simulates growing balance on a rigged web dashboard.",
                "victim_experience": "Sees high fake profits on portal screen.",
            },
            {
                "step_number": 4,
                "stage_name": "Withdrawal Freeze & Extortion",
                "description": "When victim tries to withdraw, dashboard shows 'Score Low' or 'Frozen by Exchange'. Attacker demands 30% penalty fee to release funds.",
                "attacker_action": "Extracts additional extortion payments before vanishing.",
                "victim_experience": "Realizes funds are completely unrecoverable.",
            },
        ],
        target_audience="College students, homemakers, job seekers, and young professionals.",
        warning_signs=[
            "Job offers offering high daily pay (₹3,000–₹10,000) for trivial tasks like liking videos or rating hotels.",
            "Demands to deposit money upfront to receive tasks or unlock earned commissions.",
            "Communication conducted entirely over Telegram or WhatsApp without legitimate employment contracts.",
        ],
        technical_indicators=[
            {"type": "domain", "value": "global-rating-tasks-vip.com", "safe_display": "global-rating-tasks-vip.com (Rigged Task Dashboard)", "linked_indicator_id": None},
            {"type": "domain", "value": "hotel-review-rewards-portal.top", "safe_display": "hotel-review-rewards-portal.top (Fake Review Site)", "linked_indicator_id": None},
        ],
        documented_impact="Over ₹2,000 crore defrauded across India through task-based investment syndicates during 2023-2024 as reported by the Ministry of Home Affairs.",
        protection_steps=[
            "Never pay money to get a job. Legitimate companies never charge candidates for tasks or job placement.",
            "Block and report unsolicited WhatsApp job offers originating from international or unknown numbers.",
            "Never join private Telegram channels promising daily returns on simple rating tasks.",
        ],
        victim_recovery_steps=[
            "Immediately report to 1930 and register complaint on cybercrime.gov.in with bank account and UTR numbers of recipient accounts.",
            "Preserve all Telegram chat exports, transaction slips, and URL links.",
            "Do not pay any further 'tax' or 'penalty' to release your money — it is a secondary scam.",
        ],
        legal_provisions=[
            {"instrument_id": "bns-2023", "provision": "Section 318(4), Bharatiya Nyaya Sanhita, 2023", "title": "Cheating and Dishonestly Inducing Delivery of Property", "summary": "Punishable with imprisonment up to 7 years."},
            {"instrument_id": "it-act-2000", "provision": "Section 66D, Information Technology Act, 2000", "title": "Cheating by Personation using Computer Resource", "summary": "Punishable with imprisonment up to 3 years and fine."},
        ],
        primary_source="Ministry of Home Affairs (MHA) & Cyber Crime Reporting Portal",
        source_url="https://cybercrime.gov.in/",
        published_at="2024-02-10T11:00:00Z",
        last_verified_at="2026-10-09T00:00:00Z",
        is_breaking=False,
    ),
]
