import { useEffect, useMemo, useState } from 'react'
import { Activity, Database, LoaderCircle, ShieldCheck } from 'lucide-react'
import type { ModelInfo, ScanResult } from '../types'
import { api } from '../services/api'
import { StatusBadge } from '../components/StatusBadge'

export function AnalysisPage() { const [items, setItems] = useState<ScanResult[]>([]); const [model, setModel] = useState<ModelInfo | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { Promise.all([api.getHistory(), api.getModelInfo()]).then(([history, info]) => { setItems(history); setModel(info) }).catch(e => setError(e.message)).finally(() => setLoading(false)) }, [])
  const counts = useMemo(() => ({ SAFE: items.filter(x => x.label === 'SAFE').length, SUSPICIOUS: items.filter(x => x.label === 'SUSPICIOUS').length, PHISHING: items.filter(x => x.label === 'PHISHING').length }), [items])
  if (loading) return <div className="center-state"><LoaderCircle className="spin" />Loading analysis</div>
  if (error) return <div className="page-container"><div className="error-panel">{error}</div></div>
  return <div className="page-container"><div className="page-heading"><div><p className="eyebrow">Operational view</p><h1>Analysis</h1><p>Live summary of recorded scans and the active model.</p></div></div><div className="metric-grid"><div className="metric-card"><Activity size={18} /><span>Recorded scans</span><strong>{items.length}</strong></div><div className="metric-card"><ShieldCheck size={18} /><span>Safe results</span><strong>{counts.SAFE}</strong></div><div className="metric-card"><Database size={18} /><span>Model features</span><strong>{String(model?.feature_count ?? '—')}</strong></div></div><div className="analysis-columns"><section className="panel"><div className="section-heading"><div><p className="eyebrow">Distribution</p><h2>Recorded classifications</h2></div></div>{items.length === 0 ? <div className="panel-empty">No recorded scans to summarize.</div> : <div className="distribution">{(['SAFE', 'SUSPICIOUS', 'PHISHING'] as const).map(key => <div className="distribution-row" key={key}><StatusBadge verdict={key} /><div className="distribution-bar"><span className={key.toLowerCase()} style={{ width: `${items.length ? (counts[key] / items.length) * 100 : 0}%` }} /></div><strong>{counts[key]}</strong></div>)}</div>}</section><section className="panel"><div className="section-heading"><div><p className="eyebrow">Active service</p><h2>Model information</h2></div></div><dl className="info-list"><div><dt>Version</dt><dd>{String(model?.model_version ?? 'Unavailable')}</dd></div><div><dt>Type</dt><dd>{String(model?.model_type ?? 'Unavailable')}</dd></div><div><dt>Training rows</dt><dd>{model?.dataset_rows?.toLocaleString() ?? 'Unavailable'}</dd></div><div><dt>Calibration</dt><dd>{typeof model?.calibration === 'string' ? model.calibration : 'See backend metadata'}</dd></div></dl></section></div></div>
}
